### ISSUE TITLE
Error docker run

### ISSUE THREAD

**Issue by kenziehong** [Drissdo185/Text-Summarization#1]
![image](https://github.com/Drissdo185/Text-Summarization/assets/32231963/64cee6d3-bdea-4c03-a2fa-52311c1c5705)

**Comment by Drissdo185** [comment]
You can fix that error by replacing the command "RUN mkdir /app/model" with COPY /app. (That means you just copied the folder that holds the model to the container.)

**Comment by kenziehong** [comment]
Thank you
